### ISSUE TITLE
Crash due to CandIPProducer

### ISSUE THREAD

**Issue by rpatelCERN** [TreeMaker/TreeMaker#240] opened 2017-08-23 12:38 UTC
Hey Kevin, 
In RunB-2017-v1, I am seeing a lot of jobs that crash in a module called CandIPProducer. I attached a file that contains the stdout from condor and the stack trace. 

[Run2017B-PromptReco-v1.JetHT_82_1889001.txt](https://github.com/TreeMaker/TreeMaker/files/1245374/Run2017B-PromptReco-v1.JetHT_82_1889001.txt)

**Comment by rpatelCERN** [comment] 2017-08-25 13:05
This issue is not present when using CMSSW_9_2_10, so will recommend this release for reprocessing 2017 data

**Comment by kpedro88** [comment] 2017-08-25 14:46
In that case:
* try the installation recipe w/ 9_2_10
* make sure everything merges, compiles, runs
* submit a PR updating the README to use 9_2_10 in the recipe

**Comment by rpatelCERN** [comment] 2017-08-25 15:50
Sorry I realized I was wrong, the job did run for a while but still has the same error in CMSSW_ 9_2_10, which is the latest version. So I will still need to look into this.

**Comment by rpatelCERN** [comment] 2017-08-31 12:45
This crash only happens if doZinv is set True, the other background sequences work fine. I'll check exactly which module crashes in this sequence.

**Comment by awhitbeck** [comment] 2017-08-31 13:13
it is very possible that this has to do with the reclustering for Zinv.  Frank Jensen originally put this together, maybe he could help, if you're strapped.

**Comment by fojensen** [comment] 2017-09-21 14:10
I don't really have an answer for this.

as a test file:
/store/data/Run2017B/MET/MINIAOD/PromptReco-v2/000/299/178/00000/96D1BD40-E56B-E711-BF3A-02163E0135FC.root
you can use a baby JSON to skip closer to the crash:
{"297057": [[320, 320]]}

It crashes during addJetCollection for the AK4 jets, the last module to be called is:
++++++++++++++++++ starting: processing event for module: stream = 0 label = 'pfImpactParameterTagInfosAK4PFCLEAN' id = 312

You can bypass the part where it crashes by adding:
getattr(process, 'pfImpactParameterTagInfosAK4PFCLEAN').computeGhostTrack = cms.bool(False)
below:
https://github.com/TreeMaker/TreeMaker/blob/Run2_2017/TreeMaker/python/doZinvBkg.py#L132

which controls the parameter in this code:
https://github.com/cms-sw/cmssw/blob/4bf64140bac01da27afd651efb17bea46ee0bcce/RecoBTag/ImpactParameter/plugins/IPProducer.h#L205


As an aside (?), I do find it curious that a largish EDM file called jettoolbox.root gets added to the working directory during running... For a single lumi section the jettoolbox.root file is 15MB...

**Comment by kpedro88** [comment] 2017-09-21 15:52
@fojensen thanks for investigating.

It's probably worth following up with the BTV POG about the apparent `computeGhostTrack` issue (maybe on hypernews? https://hypernews.cern.ch/HyperNews/CMS/get/btag.html). It would be helpful to make a minimal config that reproduces the crash, so they don't have to go through all the effort of installing our code.

Thanks also for pointing out the jet toolbox issue. This seems to be specific to their implementation of Tasks for CMSSW_9_X; I posted an issue: https://github.com/cms-jet/JetToolbox/issues/51.

**Comment by fojensen** [comment] 2017-10-31 16:58
I think it is a BTV issue and other people see it too:
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3574.html
and that the best temporary fix so far is something along the lines of:
process.pfImpactParameterTagInfosCA8PFCHS.computeGhostTrack = cms.bool(False)

the thread is itself an entertaining read

**Comment by kpedro88** [comment] 2017-12-05 15:29
This is fixed in https://github.com/cms-sw/cmssw/pull/21178 which will be included in `CMSSW_9_2_15`.

**Closed as completed by kpedro88** 2017-12-05 15:29 UTC
